//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ABSCENCE_CATEGORIES
    {
        public ABSCENCE_CATEGORIES()
        {
            this.ABSENCE_TYPES = new HashSet<ABSENCE_TYPES>();
            this.OFF_ABS_GROP_OFF = new HashSet<OFF_ABS_GROP_OFF>();
            this.OFF_ABS_GROUP = new HashSet<OFF_ABS_GROUP>();
        }
    
        public short ABSCENCE_CATEGORY_ID { get; set; }
        public string ABSCENCE_CATEGORY { get; set; }
    
        public virtual ICollection<ABSENCE_TYPES> ABSENCE_TYPES { get; set; }
        public virtual ICollection<OFF_ABS_GROP_OFF> OFF_ABS_GROP_OFF { get; set; }
        public virtual ICollection<OFF_ABS_GROUP> OFF_ABS_GROUP { get; set; }
    }
}
