//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCEDENT_CATEGORIES
    {
        public ACCEDENT_CATEGORIES()
        {
            this.ACCEDENTS_TYPES = new HashSet<ACCEDENTS_TYPES>();
        }
    
        public short ACCEDENT_CAT_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<short> DISPLAY_ORDER { get; set; }
    
        public virtual ICollection<ACCEDENTS_TYPES> ACCEDENTS_TYPES { get; set; }
    }
}
