//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCEDENTS
    {
        public ACCEDENTS()
        {
            this.ACCEDENT_EQUIPMENTS = new HashSet<ACCEDENT_EQUIPMENTS>();
        }
    
        public short SEQ { get; set; }
        public string FIRM_CODE { get; set; }
        public Nullable<short> ACCEDENT_TYPE_ID { get; set; }
        public Nullable<short> ACCEDENT_CAT_ID { get; set; }
        public string FIN_YEAR { get; set; }
        public Nullable<short> TRAINING_PERIOD_ID { get; set; }
        public Nullable<System.DateTime> ACCEDENT_DATE { get; set; }
        public string PLACE { get; set; }
        public string SUMMARY { get; set; }
        public string PROCEDURES { get; set; }
        public Nullable<short> RESPONSIBILITY_TYPE_ID { get; set; }
        public Nullable<short> ACC_REASON_CODE { get; set; }
    
        public virtual ICollection<ACCEDENT_EQUIPMENTS> ACCEDENT_EQUIPMENTS { get; set; }
        public virtual ACCEDENTS_TYPES ACCEDENTS_TYPES { get; set; }
        public virtual FIRMS FIRMS { get; set; }
        public virtual TRAINING_PERIODS TRAINING_PERIODS { get; set; }
    }
}
