//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMIN_GROUPS_USERS
    {
        public short PERSON_ID { get; set; }
        public short GROUP_ID { get; set; }
        public string NOTES { get; set; }
    
        public virtual ADMIN_GROUPS ADMIN_GROUPS { get; set; }
        public virtual ADMIN_USERS ADMIN_USERS { get; set; }
    }
}
