//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAILY_W
    {
        public short FUNCTION_ID { get; set; }
        public string PARENT { get; set; }
        public string FUNCTION_ANAME { get; set; }
    }
}
