//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_ITEMS_RECIEPT_SERIALS
    {
        public string FIRM_CODE { get; set; }
        public short RECIEPT_NO { get; set; }
        public short DEPARTMENT_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string SERIAL_NO { get; set; }
        public string EXISTANCE_PLACE { get; set; }
        public Nullable<short> IS_AVAILABLE { get; set; }
        public string USAGE { get; set; }
    
        public virtual FIRM_ITEMS_RECIEPT_ITEMS FIRM_ITEMS_RECIEPT_ITEMS { get; set; }
        public virtual FIRM_ITEMS_SERIALS FIRM_ITEMS_SERIALS { get; set; }
    }
}
