//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMS_ABSENCE_ITEMS
    {
        public string FIRM_CODE { get; set; }
        public short ABSENCE_TYPE_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public Nullable<short> ITEM_COUNT { get; set; }
    
        public virtual ABSENCE_TYPES ABSENCE_TYPES { get; set; }
        public virtual FIRM_ITEMS FIRM_ITEMS { get; set; }
    }
}
