//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_COUNTER_VALUES
    {
        public string FIRM_CODE { get; set; }
        public System.DateTime DURATION_START { get; set; }
        public Nullable<System.DateTime> DURATION_END { get; set; }
        public Nullable<decimal> COUNTER_VALUE { get; set; }
        public Nullable<decimal> COST { get; set; }
        public Nullable<System.DateTime> RECIEPT_DATE { get; set; }
        public Nullable<short> COUNTER_TYPE { get; set; }
    
        public virtual FIRMS FIRMS { get; set; }
    }
}
