//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_ITEMS
    {
        public FIRM_ITEMS()
        {
            this.FIRM_DESTRUCT_COMMITTEE_ITEMS = new HashSet<FIRM_DESTRUCT_COMMITTEE_ITEMS>();
            this.FIRM_ITEMS_STOCK_DATA = new HashSet<FIRM_ITEMS_STOCK_DATA>();
            this.FIRM_ITEMS_RECIEPT_ITEMS = new HashSet<FIRM_ITEMS_RECIEPT_ITEMS>();
            this.FIRM_ITEMS_SERIALS = new HashSet<FIRM_ITEMS_SERIALS>();
            this.FIRM_ITEMS_MAINTAINANCE = new HashSet<FIRM_ITEMS_MAINTAINANCE>();
            this.FIRMS_ABSENCE_ITEMS = new HashSet<FIRMS_ABSENCE_ITEMS>();
            this.FIRM_MONTH_COMM_ITEMS_NOTES = new HashSet<FIRM_MONTH_COMM_ITEMS_NOTES>();
            this.FIRMS_CALIBRATION_PLAN = new HashSet<FIRMS_CALIBRATION_PLAN>();
            this.FIRMS_GARAGE_PLAN_ITEMS = new HashSet<FIRMS_GARAGE_PLAN_ITEMS>();
            this.FIRMS_STORES_ITEMS = new HashSet<FIRMS_STORES_ITEMS>();
        }
    
        public string FIRM_CODE { get; set; }
        public string ITEM_CODE { get; set; }
        public Nullable<decimal> DEFAULT_QTY { get; set; }
        public Nullable<decimal> POLICY { get; set; }
        public Nullable<decimal> TOTAL_EXIST { get; set; }
        public Nullable<decimal> TOTAL_VALID { get; set; }
        public Nullable<decimal> DEFECTED_LOCAL { get; set; }
        public Nullable<decimal> DEFECTED_WORKSHOP { get; set; }
        public Nullable<decimal> TOTAL_STORED { get; set; }
        public string BOOKPAGE_NO { get; set; }
        public Nullable<decimal> STARTING_QTY { get; set; }
        public string STARTING_FIN_YEAR { get; set; }
        public Nullable<decimal> FROM_INVENTORIES { get; set; }
        public Nullable<decimal> TO_INVENTORIES { get; set; }
        public Nullable<decimal> FROM_OTHER_FIRMS { get; set; }
        public Nullable<decimal> TO_OTHER_FIRMS { get; set; }
        public Nullable<decimal> CONSUMED_QTY { get; set; }
        public Nullable<decimal> ADD_FROM_COMMITTEE { get; set; }
        public Nullable<decimal> REMOVE_FROM_COMMITTEE { get; set; }
        public Nullable<decimal> PERSONAL_ARM { get; set; }
    
        public virtual ICollection<FIRM_DESTRUCT_COMMITTEE_ITEMS> FIRM_DESTRUCT_COMMITTEE_ITEMS { get; set; }
        public virtual ICollection<FIRM_ITEMS_STOCK_DATA> FIRM_ITEMS_STOCK_DATA { get; set; }
        public virtual ICollection<FIRM_ITEMS_RECIEPT_ITEMS> FIRM_ITEMS_RECIEPT_ITEMS { get; set; }
        public virtual ICollection<FIRM_ITEMS_SERIALS> FIRM_ITEMS_SERIALS { get; set; }
        public virtual ICollection<FIRM_ITEMS_MAINTAINANCE> FIRM_ITEMS_MAINTAINANCE { get; set; }
        public virtual ICollection<FIRMS_ABSENCE_ITEMS> FIRMS_ABSENCE_ITEMS { get; set; }
        public virtual FIRMS FIRMS { get; set; }
        public virtual ICollection<FIRM_MONTH_COMM_ITEMS_NOTES> FIRM_MONTH_COMM_ITEMS_NOTES { get; set; }
        public virtual ICollection<FIRMS_CALIBRATION_PLAN> FIRMS_CALIBRATION_PLAN { get; set; }
        public virtual ICollection<FIRMS_GARAGE_PLAN_ITEMS> FIRMS_GARAGE_PLAN_ITEMS { get; set; }
        public virtual ICollection<FIRMS_STORES_ITEMS> FIRMS_STORES_ITEMS { get; set; }
    }
}
