//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_PROJECTS
    {
        public FIRM_PROJECTS()
        {
            this.FIRM_MISSIONS = new HashSet<FIRM_MISSIONS>();
        }
    
        public short PROJECT_ID { get; set; }
        public string PROJECT_NAME { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
    
        public virtual ICollection<FIRM_MISSIONS> FIRM_MISSIONS { get; set; }
    }
}
