//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_MONTH_COMM_ITEMS_NOTES
    {
        public string FIRM_CODE { get; set; }
        public string FIN_YEAR { get; set; }
        public short COMMITTEE_MONTH { get; set; }
        public short DEPARTMENT_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public decimal BOOK_EXIST { get; set; }
        public decimal ACTUAL_EXIST { get; set; }
        public Nullable<decimal> FAILED_COUNT { get; set; }
        public string ITEM_NOTES { get; set; }
        public short COMMITTEE_TYPE { get; set; }
        public System.DateTime COMMITTEE_DATE { get; set; }
    
        public virtual FIRM_ITEMS FIRM_ITEMS { get; set; }
        public virtual FIRM_MONTH_COMM_PASS_PLAN FIRM_MONTH_COMM_PASS_PLAN { get; set; }
    }
}
