//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_MISSIONS_ACTIONS
    {
        public string FIN_YEAR { get; set; }
        public short TRAINING_PERIOD_ID { get; set; }
        public short MISSION_ID { get; set; }
        public string FIRM_CODE { get; set; }
        public short ACTION_CODE { get; set; }
        public string PERSON_CODE { get; set; }
        public string ACTION { get; set; }
    
        public virtual FIRM_MISSIONS FIRM_MISSIONS { get; set; }
        public virtual FIRM_MISSIONS_MEMBERS FIRM_MISSIONS_MEMBERS { get; set; }
    }
}
