//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_DEPT_TYPES
    {
        public FIRM_DEPT_TYPES()
        {
            this.FIRM_DEPT_BRANCH_TYPES = new HashSet<FIRM_DEPT_BRANCH_TYPES>();
        }
    
        public short DEPT_CODE { get; set; }
        public string DEPT_NAME { get; set; }
        public string FIRM_CODE { get; set; }
    
        public virtual ICollection<FIRM_DEPT_BRANCH_TYPES> FIRM_DEPT_BRANCH_TYPES { get; set; }
    }
}
