//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMS_TAMMAM
    {
        public decimal SERIAL { get; set; }
        public string FIRM_NAME { get; set; }
        public Nullable<decimal> E3ARDA { get; set; }
        public Nullable<decimal> MTA2R { get; set; }
        public Nullable<decimal> BDL_RA7A { get; set; }
        public Nullable<decimal> SANYWA { get; set; }
        public Nullable<decimal> MARDYA { get; set; }
        public Nullable<decimal> MST { get; set; }
        public Nullable<decimal> MA2MORA_D { get; set; }
        public Nullable<decimal> MA2MORA_7 { get; set; }
        public Nullable<decimal> FERA2A { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> OUT { get; set; }
        public Nullable<decimal> IIN { get; set; }
    }
}
