//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMS_INSPECT_PASS_PLAN_DEPTS
    {
        public FIRMS_INSPECT_PASS_PLAN_DEPTS()
        {
            this.FIRMS_INSPECT_PASS_PLAN_RESULT = new HashSet<FIRMS_INSPECT_PASS_PLAN_RESULT>();
        }
    
        public short DEPARTMENT_ID { get; set; }
        public short PASS_SEQ { get; set; }
        public string FIRM_CODE { get; set; }
        public System.DateTime PLANNED_DATE { get; set; }
        public string PERSON_CODE { get; set; }
        public string FIN_YEAR { get; set; }
        public Nullable<short> TRAINING_PERIOD_ID { get; set; }
    
        public virtual FIRMS FIRMS { get; set; }
        public virtual ICollection<FIRMS_INSPECT_PASS_PLAN_RESULT> FIRMS_INSPECT_PASS_PLAN_RESULT { get; set; }
        public virtual PERSON_DATA PERSON_DATA { get; set; }
        public virtual TRAINING_PERIODS TRAINING_PERIODS { get; set; }
    }
}
