//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_ITEM_MAINTAINANCE_SERIALS
    {
        public string FIRM_CODE { get; set; }
        public string ITEM_CODE { get; set; }
        public string FIN_YEAR { get; set; }
        public short MAINTAINANCE_TYPE_ID { get; set; }
        public System.DateTime PLANNED_DATE { get; set; }
        public string SERIAL_NO { get; set; }
        public Nullable<System.DateTime> ACTUAL_DATE { get; set; }
        public Nullable<short> EXECUTION_STATUS_ID { get; set; }
        public Nullable<short> FAULT_TYPE_ID { get; set; }
        public Nullable<System.DateTime> FINISH_DATE { get; set; }
        public Nullable<short> MILES_COUNTER { get; set; }
        public Nullable<short> SEQ { get; set; }
        public Nullable<short> DOC_NO { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
    
        public virtual FIRM_ITEMS_MAINTAINANCE FIRM_ITEMS_MAINTAINANCE { get; set; }
        public virtual FIRM_ITEMS_SERIALS FIRM_ITEMS_SERIALS { get; set; }
    }
}
