//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_ITEMS_SERIALS
    {
        public FIRM_ITEMS_SERIALS()
        {
            this.FIRM_ITEM_MAINTAINANCE_SERIALS = new HashSet<FIRM_ITEM_MAINTAINANCE_SERIALS>();
            this.FIRM_ITEM_SERIAL_TIERS = new HashSet<FIRM_ITEM_SERIAL_TIERS>();
            this.FIRM_ITEM_SERIAL_TIERS1 = new HashSet<FIRM_ITEM_SERIAL_TIERS>();
            this.FIRM_ITEMS_CONTAINED_ITEMS = new HashSet<FIRM_ITEMS_CONTAINED_ITEMS>();
            this.FIRM_ITEMS_RECIEPT_SERIALS = new HashSet<FIRM_ITEMS_RECIEPT_SERIALS>();
            this.FIRMS_GARAGE_PLAN_ITEM_SER = new HashSet<FIRMS_GARAGE_PLAN_ITEM_SER>();
        }
    
        public string FIRM_CODE { get; set; }
        public string ITEM_CODE { get; set; }
        public string SERIAL_NO { get; set; }
        public Nullable<short> DELIVERY_STATUS_CODE { get; set; }
        public Nullable<short> CURRENT_STATUS_CODE { get; set; }
        public Nullable<short> USAGE_GROUP_ID { get; set; }
        public Nullable<short> DELIVERY_DOC_NO { get; set; }
        public Nullable<System.DateTime> DELIVERY_DOC_DATE { get; set; }
        public Nullable<System.DateTime> LAST_MAINT_DATA { get; set; }
        public Nullable<System.DateTime> LAST_REPAIR_DATE { get; set; }
        public string NOTES { get; set; }
        public string RIGHT_SIGN { get; set; }
        public string LEFT_SIGN { get; set; }
        public string BODY_NOMBER { get; set; }
        public string DELIVERY_FIN_YEAR { get; set; }
        public Nullable<short> IS_AVAILABLE { get; set; }
        public string CYLINDER_AGE { get; set; }
        public Nullable<System.DateTime> BATTERY_DELIVERY_DATE { get; set; }
        public string ITEM_ASSINMENT { get; set; }
        public string CYLINDER_SER { get; set; }
        public string DRIVER_CODE { get; set; }
        public string CARRIER_SERIAL_NO { get; set; }
        public Nullable<short> LAST_MAINTAINANCE_TYPE_ID { get; set; }
        public Nullable<short> LAST_REPAIR_TYPE_ID { get; set; }
        public string CYLINDER_ITEM_CODE { get; set; }
        public string CARRIER_ITEM_CODE { get; set; }
        public string TAWREED_ORDER_NO { get; set; }
        public Nullable<System.DateTime> WORK_START_DATE { get; set; }
    
        public virtual FINANCIAL_YEAR FINANCIAL_YEAR { get; set; }
        public virtual ICollection<FIRM_ITEM_MAINTAINANCE_SERIALS> FIRM_ITEM_MAINTAINANCE_SERIALS { get; set; }
        public virtual ICollection<FIRM_ITEM_SERIAL_TIERS> FIRM_ITEM_SERIAL_TIERS { get; set; }
        public virtual ICollection<FIRM_ITEM_SERIAL_TIERS> FIRM_ITEM_SERIAL_TIERS1 { get; set; }
        public virtual FIRM_ITEMS FIRM_ITEMS { get; set; }
        public virtual ICollection<FIRM_ITEMS_CONTAINED_ITEMS> FIRM_ITEMS_CONTAINED_ITEMS { get; set; }
        public virtual ICollection<FIRM_ITEMS_RECIEPT_SERIALS> FIRM_ITEMS_RECIEPT_SERIALS { get; set; }
        public virtual ICollection<FIRMS_GARAGE_PLAN_ITEM_SER> FIRMS_GARAGE_PLAN_ITEM_SER { get; set; }
    }
}
