//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMS_GARAGE_PLAN_ITEMS
    {
        public FIRMS_GARAGE_PLAN_ITEMS()
        {
            this.FIRMS_GARAGE_PLAN_ITEM_SER = new HashSet<FIRMS_GARAGE_PLAN_ITEM_SER>();
        }
    
        public string FIN_YEAR { get; set; }
        public string FIRM_CODE { get; set; }
        public long MONTH_ID { get; set; }
        public short WEEK_NO { get; set; }
        public string ITEM_CODE { get; set; }
        public Nullable<short> DEPARTMENT_ID { get; set; }
        public Nullable<decimal> PLANNED_QTY { get; set; }
        public Nullable<decimal> ACTUAL_QTY { get; set; }
        public string PLACE_FIRM_CODE { get; set; }
        public Nullable<short> HAS_DETAILS { get; set; }
    
        public virtual FIRM_ITEMS FIRM_ITEMS { get; set; }
        public virtual FIRMS_GARAGE_PLAN FIRMS_GARAGE_PLAN { get; set; }
        public virtual ICollection<FIRMS_GARAGE_PLAN_ITEM_SER> FIRMS_GARAGE_PLAN_ITEM_SER { get; set; }
    }
}
