//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_MISSIONS
    {
        public FIRM_MISSIONS()
        {
            this.FIRM_MISSIONS_MEMBERS = new HashSet<FIRM_MISSIONS_MEMBERS>();
            this.FIRM_MISSIONS_ACTIONS = new HashSet<FIRM_MISSIONS_ACTIONS>();
        }
    
        public string FIRM_CODE { get; set; }
        public string FIN_YEAR { get; set; }
        public short TRAINING_PERIOD_ID { get; set; }
        public short MISSION_ID { get; set; }
        public string MISSION_FIRM_CODE { get; set; }
        public string FIRM_NAME { get; set; }
        public Nullable<short> PROJECT_ID { get; set; }
        public string INTRODUCTION { get; set; }
        public string FINAL { get; set; }
        public string SUBJECT { get; set; }
        public string DISTRIBUTION { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public Nullable<short> MISSION_TYPE { get; set; }
        public Nullable<short> IS_PLANNED { get; set; }
        public Nullable<short> IS_DONE { get; set; }
    
        public virtual FIRMS FIRMS { get; set; }
        public virtual TRAINING_PERIODS TRAINING_PERIODS { get; set; }
        public virtual ICollection<FIRM_MISSIONS_MEMBERS> FIRM_MISSIONS_MEMBERS { get; set; }
        public virtual ICollection<FIRM_MISSIONS_ACTIONS> FIRM_MISSIONS_ACTIONS { get; set; }
        public virtual FIRMS FIRMS1 { get; set; }
        public virtual FIRM_PROJECTS FIRM_PROJECTS { get; set; }
    }
}
