//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_ITEMS_MAINTAINANCE
    {
        public FIRM_ITEMS_MAINTAINANCE()
        {
            this.FIRM_ITEM_MAINTAINANCE_SERIALS = new HashSet<FIRM_ITEM_MAINTAINANCE_SERIALS>();
            this.FIRM_ITEMS_FAULTS = new HashSet<FIRM_ITEMS_FAULTS>();
        }
    
        public string FIRM_CODE { get; set; }
        public string ITEM_CODE { get; set; }
        public string FIN_YEAR { get; set; }
        public System.DateTime PLANNED_DATE { get; set; }
        public short MAINTAINANCE_TYPE_ID { get; set; }
        public Nullable<System.DateTime> ACTUAL_DATE { get; set; }
        public Nullable<System.DateTime> FINISH_DATE { get; set; }
        public Nullable<decimal> PLANNED_QTY { get; set; }
        public Nullable<decimal> FINISHED_QTY { get; set; }
        public Nullable<short> FAULT_TYPE_ID { get; set; }
        public Nullable<short> EXECUTION_STATUS_ID { get; set; }
        public Nullable<decimal> ACTUAL_QTY { get; set; }
        public string APPROVAL_NO { get; set; }
        public Nullable<short> DOC_NO { get; set; }
        public Nullable<System.DateTime> APPROVAL_DATE { get; set; }
        public Nullable<System.DateTime> DOC_DATE { get; set; }
        public string PLACE_FIRM_CODE { get; set; }
        public Nullable<System.DateTime> LAST_CHECK_DATE { get; set; }
        public Nullable<short> HAS_DETAILS { get; set; }
    
        public virtual FINANCIAL_YEAR FINANCIAL_YEAR { get; set; }
        public virtual ICollection<FIRM_ITEM_MAINTAINANCE_SERIALS> FIRM_ITEM_MAINTAINANCE_SERIALS { get; set; }
        public virtual FIRM_ITEMS FIRM_ITEMS { get; set; }
        public virtual ICollection<FIRM_ITEMS_FAULTS> FIRM_ITEMS_FAULTS { get; set; }
    }
}
