//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_MONTHLY_COMMITTEES
    {
        public FIRM_MONTHLY_COMMITTEES()
        {
            this.FIRM_MONTH_COMM_PASS_PLAN = new HashSet<FIRM_MONTH_COMM_PASS_PLAN>();
        }
    
        public string FIRM_CODE { get; set; }
        public string FIN_YEAR { get; set; }
        public short COMMITTEE_MONTH { get; set; }
        public string HEAD_PERSON_CODE { get; set; }
        public string MEMBER1_PERSON_CODE { get; set; }
        public string MEMBER2_PERSON_CODE { get; set; }
        public string SALARY_PERSON_CODE { get; set; }
        public string SHOP_PERSON_CODE { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public short COMMITTEE_TYPE { get; set; }
        public System.DateTime COMMITTEE_DATE { get; set; }
    
        public virtual FINANCIAL_YEAR FINANCIAL_YEAR { get; set; }
        public virtual ICollection<FIRM_MONTH_COMM_PASS_PLAN> FIRM_MONTH_COMM_PASS_PLAN { get; set; }
        public virtual PERSON_DATA PERSON_DATA { get; set; }
        public virtual PERSON_DATA PERSON_DATA1 { get; set; }
        public virtual PERSON_DATA PERSON_DATA2 { get; set; }
        public virtual FIRMS FIRMS { get; set; }
        public virtual PERSON_DATA PERSON_DATA3 { get; set; }
        public virtual PERSON_DATA PERSON_DATA4 { get; set; }
    }
}
