//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_DEPTS_RESPONSIBLES
    {
        public FIRM_DEPTS_RESPONSIBLES()
        {
            this.FIRM_DESTRUCT_COMMITTEES = new HashSet<FIRM_DESTRUCT_COMMITTEES>();
        }
    
        public string FIRM_CODE { get; set; }
        public short DEPARTMENT_ID { get; set; }
        public string OFF1_PERSON_CODE { get; set; }
        public string OFF2_PERSON_CODE { get; set; }
        public string SOL1_PERSON_CODE { get; set; }
        public string SOL2_PERSON_CODE { get; set; }
    
        public virtual PERSON_DATA PERSON_DATA { get; set; }
        public virtual PERSON_DATA PERSON_DATA1 { get; set; }
        public virtual PERSON_DATA PERSON_DATA2 { get; set; }
        public virtual PERSON_DATA PERSON_DATA3 { get; set; }
        public virtual FIRMS FIRMS { get; set; }
        public virtual ICollection<FIRM_DESTRUCT_COMMITTEES> FIRM_DESTRUCT_COMMITTEES { get; set; }
    }
}
