//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRM_KANTEENS
    {
        public string FIRM_CODE { get; set; }
        public short KANTEEN_SERIAL { get; set; }
        public string KANTEEN_NAME { get; set; }
        public Nullable<short> KANTEEN_TYPE_CODE { get; set; }
    }
}
