//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FIRMS_CATEGORIES
    {
        public short FIRM_CAT_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<short> DISPLAY_ORDER { get; set; }
    }
}
