//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HD_CALL_DETAILS
    {
        public long CALLSERIAL { get; set; }
        public string CALLENDTIME { get; set; }
        public string CALLSTARTTIME { get; set; }
        public string CALLDATE { get; set; }
        public string CALLERNAME { get; set; }
        public string ACTIONNAME { get; set; }
        public string CLASSIFICATIONNAME { get; set; }
        public string UNITNAME { get; set; }
        public string INITIAL_AGENT_NAME { get; set; }
        public string FIRM_CODE { get; set; }
        public decimal CALLERCODE { get; set; }
        public string INITIALAGENTCODE { get; set; }
        public string USER_CREATION { get; set; }
        public string TRANSFERREDTOOFFICERCODE { get; set; }
    }
}
