//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFF_ABS_GROUP
    {
        public OFF_ABS_GROUP()
        {
            this.OFF_ABS_GROP_OFF = new HashSet<OFF_ABS_GROP_OFF>();
            this.OFF_ABS_STEPS = new HashSet<OFF_ABS_STEPS>();
        }
    
        public decimal OFF_ABS_GROUP_ID { get; set; }
        public string FIRMS_CODE { get; set; }
        public Nullable<short> ABSCENCE_CATEGORY_ID { get; set; }
        public string OFF_ABS_GROUP_NAME { get; set; }
        public Nullable<short> ACTIV_F { get; set; }
        public string PARANT_FIRMS_CODE { get; set; }
        public Nullable<short> UNIT_DEF_GROUP { get; set; }
        public string UNIT_CODE_N { get; set; }
    
        public virtual ABSCENCE_CATEGORIES ABSCENCE_CATEGORIES { get; set; }
        public virtual FIRMS FIRMS { get; set; }
        public virtual FIRMS FIRMS1 { get; set; }
        public virtual ICollection<OFF_ABS_GROP_OFF> OFF_ABS_GROP_OFF { get; set; }
        public virtual ICollection<OFF_ABS_STEPS> OFF_ABS_STEPS { get; set; }
    }
}
