//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFF_ABS_GROP_OFF
    {
        public decimal OFF_ABS_GROUP_OFF_ID { get; set; }
        public decimal OFF_ABS_GROUP_ID { get; set; }
        public Nullable<long> OFF_SKELETON_OFFICERS_ID { get; set; }
        public Nullable<short> ABS_CAT_ID { get; set; }
        public string PERSON_DATA_ID { get; set; }
    
        public virtual ABSCENCE_CATEGORIES ABSCENCE_CATEGORIES { get; set; }
        public virtual OFF_ABS_GROUP OFF_ABS_GROUP { get; set; }
        public virtual PERSON_DATA PERSON_DATA { get; set; }
    }
}
