//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONS_RANKING
    {
        public string PERSON_CODE { get; set; }
        public short RANK_ID { get; set; }
        public short RANK_CAT_ID { get; set; }
        public short PERSON_CAT_ID { get; set; }
        public string FIRM_CODE { get; set; }
        public Nullable<short> EXECUTION_STATUS_ID { get; set; }
        public Nullable<System.DateTime> RANK_DATE { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public Nullable<System.DateTime> NEXT_RANK_DATE { get; set; }
    
        public virtual PERSON_DATA PERSON_DATA { get; set; }
        public virtual RANKS RANKS { get; set; }
    }
}
