//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_PUNISHMENT_EXECUTION
    {
        public short SEQ { get; set; }
        public string PERSON_CODE { get; set; }
        public Nullable<short> JAIL_ID { get; set; }
        public string FIRM_CODE { get; set; }
        public Nullable<short> YEAR_COUNT { get; set; }
        public Nullable<short> MONTH_COUNT { get; set; }
        public Nullable<short> DAY_COUNT { get; set; }
        public Nullable<System.DateTime> EXECUTION_DATE { get; set; }
        public Nullable<short> CASE_NO { get; set; }
        public Nullable<short> CASE_YEAR { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string CRIME { get; set; }
        public string SUBJECTS { get; set; }
    
        public virtual PERSON_DATA PERSON_DATA { get; set; }
    }
}
