//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_DAILY_ENTRY_FEE
    {
        public decimal SEQ { get; set; }
        public string FIRM_CODE { get; set; }
        public Nullable<System.DateTime> FEE_TIME { get; set; }
        public Nullable<decimal> FEE_PERIOD { get; set; }
        public string FEE_NAME { get; set; }
        public Nullable<decimal> FEE_VAL { get; set; }
    }
}
