//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_VACATIONS
    {
        public PERSON_VACATIONS()
        {
            this.PERSON_VACATIONS_DET = new HashSet<PERSON_VACATIONS_DET>();
        }
    
        public short SEQ { get; set; }
        public string FIRM_CODE { get; set; }
        public string PERSON_CODE { get; set; }
        public Nullable<short> RANK_ID { get; set; }
        public Nullable<short> RANK_CAT_ID { get; set; }
        public Nullable<short> PERSON_CAT_ID { get; set; }
        public Nullable<short> VACATION_TYPE_ID { get; set; }
        public Nullable<System.DateTime> REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public string OTHER_PERSON_CODE { get; set; }
        public Nullable<short> RAN_RANK_ID { get; set; }
        public Nullable<short> RAN_RANK_CAT_ID { get; set; }
        public Nullable<short> RAN_PERSON_CAT_ID { get; set; }
        public string SUPERVISOR_CODE { get; set; }
        public string SUPERVISOR_NOTES { get; set; }
        public Nullable<short> SUPERVISOR_DECESION { get; set; }
        public string PLANNING_CODE { get; set; }
        public string PLANNING_NOTES { get; set; }
        public Nullable<short> PLANNING_DECESION { get; set; }
        public string VICE_COMMAND_CODE { get; set; }
        public string VICE_COMMAND_NOTES { get; set; }
        public Nullable<short> VICE_COMMAND_DECESION { get; set; }
        public string COMANDER_CODE { get; set; }
        public string COMANDER_NOTES { get; set; }
        public Nullable<short> COMANDER_DECESION { get; set; }
        public Nullable<System.DateTime> ACTUAL_START { get; set; }
        public Nullable<System.DateTime> ACTUAL_END { get; set; }
        public string APPROVED_BY { get; set; }
        public string APPROVAL_NO { get; set; }
        public Nullable<System.DateTime> APPROVAL_DATE { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<System.DateTime> EXCHANGE_FOR_DATE { get; set; }
        public Nullable<short> FLAG_PLAN { get; set; }
        public Nullable<decimal> OTHER_PER_DECS { get; set; }
        public Nullable<System.DateTime> CR_TIME { get; set; }
    
        public virtual FIRMS FIRMS { get; set; }
        public virtual PERSON_DATA PERSON_DATA { get; set; }
        public virtual PERSON_DATA PERSON_DATA1 { get; set; }
        public virtual PERSON_DATA PERSON_DATA2 { get; set; }
        public virtual PERSON_DATA PERSON_DATA3 { get; set; }
        public virtual PERSON_DATA PERSON_DATA4 { get; set; }
        public virtual PERSON_DATA PERSON_DATA5 { get; set; }
        public virtual RANKS RANKS { get; set; }
        public virtual RANKS RANKS1 { get; set; }
        public virtual VACATION_TYPES VACATION_TYPES { get; set; }
        public virtual ICollection<PERSON_VACATIONS_DET> PERSON_VACATIONS_DET { get; set; }
    }
}
