//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_DATA
    {
        public PERSON_DATA()
        {
            this.FIRM_DEPTS_RESPONSIBLES = new HashSet<FIRM_DEPTS_RESPONSIBLES>();
            this.FIRM_DEPTS_RESPONSIBLES1 = new HashSet<FIRM_DEPTS_RESPONSIBLES>();
            this.FIRM_DEPTS_RESPONSIBLES2 = new HashSet<FIRM_DEPTS_RESPONSIBLES>();
            this.FIRM_DEPTS_RESPONSIBLES3 = new HashSet<FIRM_DEPTS_RESPONSIBLES>();
            this.FIRM_DESTRUCT_COMMITTEES = new HashSet<FIRM_DESTRUCT_COMMITTEES>();
            this.FIRM_DESTRUCT_COMMITTEES1 = new HashSet<FIRM_DESTRUCT_COMMITTEES>();
            this.FIRM_DESTRUCT_COMMITTEES2 = new HashSet<FIRM_DESTRUCT_COMMITTEES>();
            this.FIRM_ITEMS_DOCUMENTS = new HashSet<FIRM_ITEMS_DOCUMENTS>();
            this.FIRM_ITEMS_RECIEPTS = new HashSet<FIRM_ITEMS_RECIEPTS>();
            this.FIRM_ITEMS_RECIEPTS1 = new HashSet<FIRM_ITEMS_RECIEPTS>();
            this.FIRM_ITEMS_RECIEPTS2 = new HashSet<FIRM_ITEMS_RECIEPTS>();
            this.FIRM_ITEMS_RECIEPTS3 = new HashSet<FIRM_ITEMS_RECIEPTS>();
            this.FIRM_MISSIONS_DET = new HashSet<FIRM_MISSIONS_DET>();
            this.FIRM_MISSIONS_MEMBERS = new HashSet<FIRM_MISSIONS_MEMBERS>();
            this.FIRM_MONTH_COMM_PASS_PLAN = new HashSet<FIRM_MONTH_COMM_PASS_PLAN>();
            this.FIRM_MONTH_COMM_PASS_PLAN1 = new HashSet<FIRM_MONTH_COMM_PASS_PLAN>();
            this.FIRM_MONTHLY_COMMITTEES = new HashSet<FIRM_MONTHLY_COMMITTEES>();
            this.FIRM_MONTHLY_COMMITTEES1 = new HashSet<FIRM_MONTHLY_COMMITTEES>();
            this.FIRM_MONTHLY_COMMITTEES2 = new HashSet<FIRM_MONTHLY_COMMITTEES>();
            this.FIRM_MONTHLY_COMMITTEES3 = new HashSet<FIRM_MONTHLY_COMMITTEES>();
            this.FIRM_MONTHLY_COMMITTEES4 = new HashSet<FIRM_MONTHLY_COMMITTEES>();
            this.FIRMS_ABSENCE_EXCHANGE = new HashSet<FIRMS_ABSENCE_EXCHANGE>();
            this.FIRMS_ABSENCE_EXCHANGE1 = new HashSet<FIRMS_ABSENCE_EXCHANGE>();
            this.FIRMS_ABSENCES_PERSONS = new HashSet<FIRMS_ABSENCES_PERSONS>();
            this.FIRMS_ABSENCES_PERSONS_DET = new HashSet<FIRMS_ABSENCES_PERSONS_DET>();
            this.FIRMS_INSPECT_PASS_PLAN = new HashSet<FIRMS_INSPECT_PASS_PLAN>();
            this.FIRMS_INSPECT_PASS_PLAN1 = new HashSet<FIRMS_INSPECT_PASS_PLAN>();
            this.FIRMS_INSPECT_PASS_PLAN_DEPTS = new HashSet<FIRMS_INSPECT_PASS_PLAN_DEPTS>();
            this.OFF_ABS_GROP_OFF = new HashSet<OFF_ABS_GROP_OFF>();
            this.PERSON_ACCENDENTS = new HashSet<PERSON_ACCENDENTS>();
            this.PERSON_ARMY_COMM_INTERVIEWS = new HashSet<PERSON_ARMY_COMM_INTERVIEWS>();
            this.PERSON_BATTELES = new HashSet<PERSON_BATTELES>();
            this.PERSON_COMPLAINS = new HashSet<PERSON_COMPLAINS>();
            this.PERSON_KAFAA_REPORT = new HashSet<PERSON_KAFAA_REPORT>();
            this.PERSON_KAFAA_REPORT1 = new HashSet<PERSON_KAFAA_REPORT>();
            this.PERSON_KAFAA_REPORT2 = new HashSet<PERSON_KAFAA_REPORT>();
            this.PERSON_KAFAA_REPORT3 = new HashSet<PERSON_KAFAA_REPORT>();
            this.PERSON_HEALTH_STATUS = new HashSet<PERSON_HEALTH_STATUS>();
            this.PERSON_HOSPITALS = new HashSet<PERSON_HOSPITALS>();
            this.PERSON_ILLEGAL_ABSCENCES = new HashSet<PERSON_ILLEGAL_ABSCENCES>();
            this.PERSON_IT_QUALIFICATIONS = new HashSet<PERSON_IT_QUALIFICATIONS>();
            this.PERSON_IT_PROJECTS = new HashSet<PERSON_IT_PROJECTS>();
            this.PERSON_INVESTGATIONS = new HashSet<PERSON_INVESTGATIONS>();
            this.PERSON_JOBS = new HashSet<PERSON_JOBS>();
            this.PERSON_LANGUAGES = new HashSet<PERSON_LANGUAGES>();
            this.PERSON_MEDALS = new HashSet<PERSON_MEDALS>();
            this.PERSON_MEASURES = new HashSet<PERSON_MEASURES>();
            this.PERSON_PROPERTIES = new HashSet<PERSON_PROPERTIES>();
            this.PERSON_PUNISHMENTS = new HashSet<PERSON_PUNISHMENTS>();
            this.PERSON_PUNISHMENT_EXECUTION = new HashSet<PERSON_PUNISHMENT_EXECUTION>();
            this.PERSON_RANKING_TESTS = new HashSet<PERSON_RANKING_TESTS>();
            this.PERSON_RELIVANTS = new HashSet<PERSON_RELIVANTS>();
            this.PERSON_REPORTS = new HashSet<PERSON_REPORTS>();
            this.PERSON_SECRET_REPORTS = new HashSet<PERSON_SECRET_REPORTS>();
            this.PERSON_STUDIES = new HashSet<PERSON_STUDIES>();
            this.PERSON_SOCIAL_PROBLEMS = new HashSet<PERSON_SOCIAL_PROBLEMS>();
            this.PERSON_UNIV_STUDIES = new HashSet<PERSON_UNIV_STUDIES>();
            this.PERSON_VACATIONS = new HashSet<PERSON_VACATIONS>();
            this.PERSON_VACATIONS1 = new HashSet<PERSON_VACATIONS>();
            this.PERSON_VACATIONS2 = new HashSet<PERSON_VACATIONS>();
            this.PERSON_VACATIONS3 = new HashSet<PERSON_VACATIONS>();
            this.PERSON_VACATIONS4 = new HashSet<PERSON_VACATIONS>();
            this.PERSON_VACATIONS5 = new HashSet<PERSON_VACATIONS>();
            this.PERSONS_GIFTS = new HashSet<PERSONS_GIFTS>();
            this.PERSONS_RANKING = new HashSet<PERSONS_RANKING>();
            this.PERSONS_TRAVELS = new HashSet<PERSONS_TRAVELS>();
            this.PERSONS_RELIVENTS_TRAVELS = new HashSet<PERSONS_RELIVENTS_TRAVELS>();
            this.PERSON_PAYING_SYNDICATE = new HashSet<PERSON_PAYING_SYNDICATE>();
            this.PERSON_PROGRAMMING_TOOLS = new HashSet<PERSON_PROGRAMMING_TOOLS>();
            this.PERSON_PROJECTS = new HashSet<PERSON_PROJECTS>();
            this.PERSON_VACATIONS_DET = new HashSet<PERSON_VACATIONS_DET>();
        }
    
        public string PERSON_CODE { get; set; }
        public Nullable<short> RANK_ID { get; set; }
        public Nullable<short> DEPARTMENT_ID { get; set; }
        public Nullable<short> JOB_TYPE_ID { get; set; }
        public Nullable<short> GOVERNERATE_ID { get; set; }
        public Nullable<short> SECTOR_ID { get; set; }
        public Nullable<short> RELIGION_ID { get; set; }
        public Nullable<short> BLOOD_TYPE_ID { get; set; }
        public Nullable<short> AGE_CATEGORY_ID { get; set; }
        public Nullable<short> FACULTY_BRANCH_ID { get; set; }
        public Nullable<short> FACULTY_ID { get; set; }
        public Nullable<short> FAC_DEPARTMENT_ID { get; set; }
        public Nullable<short> UNIVERSITY_ID { get; set; }
        public Nullable<short> ID_TYPE_ID { get; set; }
        public Nullable<short> PARENT_STATUS_ID { get; set; }
        public string FIRM_CODE { get; set; }
        public Nullable<short> SOCIAL_STATE_ID { get; set; }
        public Nullable<short> RANK_CAT_ID { get; set; }
        public Nullable<short> PERSON_CAT_ID { get; set; }
        public Nullable<short> SPECIALIZATION_ID { get; set; }
        public Nullable<short> CATEGORY_ID { get; set; }
        public string PERSON_NAME { get; set; }
        public string ADDERESS { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE_2 { get; set; }
        public string ID_NO { get; set; }
        public string SORT_NO { get; set; }
        public string BIRTH_PLACE { get; set; }
        public Nullable<short> SONS_COUNT { get; set; }
        public Nullable<short> DAUGHTERS_COUNT { get; set; }
        public Nullable<short> ARKAN_HARB { get; set; }
        public string COMMUNITY_NO { get; set; }
        public Nullable<short> MARRIGE_CONT { get; set; }
        public Nullable<short> SEX { get; set; }
        public Nullable<System.DateTime> JOIN_DATE { get; set; }
        public Nullable<System.DateTime> LEAVE_DATE { get; set; }
        public Nullable<System.DateTime> NEXT_RANK_DATE { get; set; }
        public Nullable<System.DateTime> CURRENT_RANK_DATE { get; set; }
        public string GRADUATION_NAME { get; set; }
        public Nullable<System.DateTime> REDEEF_DATE { get; set; }
        public Nullable<short> CLT_ID { get; set; }
        public Nullable<short> CERTIFICATE { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public Nullable<short> OUT_UN_FORCE { get; set; }
        public Nullable<short> EDUCATION_LEVEL_ID { get; set; }
        public Nullable<short> EDUCATION_CERTIFICATE_ID { get; set; }
        public Nullable<short> EDUCATION_SPEC_ID { get; set; }
        public Nullable<short> CIVIL_JOB_ID { get; set; }
        public Nullable<short> SHOE_SIZE { get; set; }
        public string SUIT_SIZE { get; set; }
        public Nullable<short> OVERALL_SIZE { get; set; }
        public string MASK_SIZE { get; set; }
        public Nullable<short> RESIGN_REQUEST { get; set; }
        public Nullable<System.DateTime> RESIGN_REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> RESIGN_ACCEPTANCE_DATE { get; set; }
        public Nullable<System.DateTime> RANK_RENEW_DATE { get; set; }
        public Nullable<short> FEED_REPLACE { get; set; }
        public Nullable<short> SECONDRY_JOB_TYPE_ID { get; set; }
        public Nullable<short> RECRUTING_REGION_ID { get; set; }
        public string PERSONAL_ID_NO { get; set; }
        public Nullable<short> FIELD_SERVICE_ABILITY { get; set; }
        public Nullable<short> OUT_SERVICE_REASON_ID { get; set; }
        public Nullable<short> VACATION_MODEL_ID { get; set; }
        public Nullable<short> BORROW_STATUS { get; set; }
        public Nullable<short> SPECIALIZATION_LEVEL_ID { get; set; }
        public string BORROW_FIRM_CODE { get; set; }
        public string PRACTICAL_EXPERIENCE { get; set; }
        public Nullable<short> IS_READYTOEXAM { get; set; }
        public string BORROW_ORDER_NO { get; set; }
        public string DEATH_PLACE { get; set; }
        public string DEATH_REASON { get; set; }
        public Nullable<System.DateTime> DEATH_DATE { get; set; }
        public string OUT_SERVICE_ORDER_NO { get; set; }
        public Nullable<System.DateTime> OUT_SERVICE_ORDER_DATE { get; set; }
        public string APLLICATION_21_NO { get; set; }
        public string APLLICATION_26_NO { get; set; }
        public Nullable<short> DEPT_CODE { get; set; }
        public Nullable<short> BRANCH_CODE { get; set; }
        public Nullable<short> PAYING_SYNDICATE_SITUATION { get; set; }
        public string SYNDICATE_NAME { get; set; }
        public string ARC_CODE { get; set; }
        public Nullable<int> ARC_SERIAL { get; set; }
        public string SARYA { get; set; }
        public string EFADA_CODE { get; set; }
        public Nullable<System.DateTime> EFADA_DATE { get; set; }
        public string AMN_STATE { get; set; }
        public string NAFSY { get; set; }
        public string ADDERESS2 { get; set; }
        public Nullable<System.DateTime> NOZOM_DATE { get; set; }
        public Nullable<int> WEAPON_NO { get; set; }
        public string EXTENSION { get; set; }
        public string PHONE_3 { get; set; }
        public string TRANSFER_NO { get; set; }
    
        public virtual FIRM_DEPT_BRANCH_TYPES FIRM_DEPT_BRANCH_TYPES { get; set; }
        public virtual ICollection<FIRM_DEPTS_RESPONSIBLES> FIRM_DEPTS_RESPONSIBLES { get; set; }
        public virtual ICollection<FIRM_DEPTS_RESPONSIBLES> FIRM_DEPTS_RESPONSIBLES1 { get; set; }
        public virtual ICollection<FIRM_DEPTS_RESPONSIBLES> FIRM_DEPTS_RESPONSIBLES2 { get; set; }
        public virtual ICollection<FIRM_DEPTS_RESPONSIBLES> FIRM_DEPTS_RESPONSIBLES3 { get; set; }
        public virtual ICollection<FIRM_DESTRUCT_COMMITTEES> FIRM_DESTRUCT_COMMITTEES { get; set; }
        public virtual ICollection<FIRM_DESTRUCT_COMMITTEES> FIRM_DESTRUCT_COMMITTEES1 { get; set; }
        public virtual ICollection<FIRM_DESTRUCT_COMMITTEES> FIRM_DESTRUCT_COMMITTEES2 { get; set; }
        public virtual ICollection<FIRM_ITEMS_DOCUMENTS> FIRM_ITEMS_DOCUMENTS { get; set; }
        public virtual ICollection<FIRM_ITEMS_RECIEPTS> FIRM_ITEMS_RECIEPTS { get; set; }
        public virtual ICollection<FIRM_ITEMS_RECIEPTS> FIRM_ITEMS_RECIEPTS1 { get; set; }
        public virtual ICollection<FIRM_ITEMS_RECIEPTS> FIRM_ITEMS_RECIEPTS2 { get; set; }
        public virtual ICollection<FIRM_ITEMS_RECIEPTS> FIRM_ITEMS_RECIEPTS3 { get; set; }
        public virtual ICollection<FIRM_MISSIONS_DET> FIRM_MISSIONS_DET { get; set; }
        public virtual ICollection<FIRM_MISSIONS_MEMBERS> FIRM_MISSIONS_MEMBERS { get; set; }
        public virtual ICollection<FIRM_MONTH_COMM_PASS_PLAN> FIRM_MONTH_COMM_PASS_PLAN { get; set; }
        public virtual ICollection<FIRM_MONTH_COMM_PASS_PLAN> FIRM_MONTH_COMM_PASS_PLAN1 { get; set; }
        public virtual ICollection<FIRM_MONTHLY_COMMITTEES> FIRM_MONTHLY_COMMITTEES { get; set; }
        public virtual ICollection<FIRM_MONTHLY_COMMITTEES> FIRM_MONTHLY_COMMITTEES1 { get; set; }
        public virtual ICollection<FIRM_MONTHLY_COMMITTEES> FIRM_MONTHLY_COMMITTEES2 { get; set; }
        public virtual ICollection<FIRM_MONTHLY_COMMITTEES> FIRM_MONTHLY_COMMITTEES3 { get; set; }
        public virtual ICollection<FIRM_MONTHLY_COMMITTEES> FIRM_MONTHLY_COMMITTEES4 { get; set; }
        public virtual FIRMS FIRMS { get; set; }
        public virtual ICollection<FIRMS_ABSENCE_EXCHANGE> FIRMS_ABSENCE_EXCHANGE { get; set; }
        public virtual ICollection<FIRMS_ABSENCE_EXCHANGE> FIRMS_ABSENCE_EXCHANGE1 { get; set; }
        public virtual ICollection<FIRMS_ABSENCES_PERSONS> FIRMS_ABSENCES_PERSONS { get; set; }
        public virtual ICollection<FIRMS_ABSENCES_PERSONS_DET> FIRMS_ABSENCES_PERSONS_DET { get; set; }
        public virtual ICollection<FIRMS_INSPECT_PASS_PLAN> FIRMS_INSPECT_PASS_PLAN { get; set; }
        public virtual ICollection<FIRMS_INSPECT_PASS_PLAN> FIRMS_INSPECT_PASS_PLAN1 { get; set; }
        public virtual ICollection<FIRMS_INSPECT_PASS_PLAN_DEPTS> FIRMS_INSPECT_PASS_PLAN_DEPTS { get; set; }
        public virtual ICollection<OFF_ABS_GROP_OFF> OFF_ABS_GROP_OFF { get; set; }
        public virtual ICollection<PERSON_ACCENDENTS> PERSON_ACCENDENTS { get; set; }
        public virtual ICollection<PERSON_ARMY_COMM_INTERVIEWS> PERSON_ARMY_COMM_INTERVIEWS { get; set; }
        public virtual ICollection<PERSON_BATTELES> PERSON_BATTELES { get; set; }
        public virtual ICollection<PERSON_COMPLAINS> PERSON_COMPLAINS { get; set; }
        public virtual ICollection<PERSON_KAFAA_REPORT> PERSON_KAFAA_REPORT { get; set; }
        public virtual ICollection<PERSON_KAFAA_REPORT> PERSON_KAFAA_REPORT1 { get; set; }
        public virtual ICollection<PERSON_KAFAA_REPORT> PERSON_KAFAA_REPORT2 { get; set; }
        public virtual ICollection<PERSON_KAFAA_REPORT> PERSON_KAFAA_REPORT3 { get; set; }
        public virtual PERSON_SPECIALIZATIONS PERSON_SPECIALIZATIONS { get; set; }
        public virtual RANKS RANKS { get; set; }
        public virtual RELIGIONS RELIGIONS { get; set; }
        public virtual ICollection<PERSON_HEALTH_STATUS> PERSON_HEALTH_STATUS { get; set; }
        public virtual ICollection<PERSON_HOSPITALS> PERSON_HOSPITALS { get; set; }
        public virtual ICollection<PERSON_ILLEGAL_ABSCENCES> PERSON_ILLEGAL_ABSCENCES { get; set; }
        public virtual ICollection<PERSON_IT_QUALIFICATIONS> PERSON_IT_QUALIFICATIONS { get; set; }
        public virtual ICollection<PERSON_IT_PROJECTS> PERSON_IT_PROJECTS { get; set; }
        public virtual ICollection<PERSON_INVESTGATIONS> PERSON_INVESTGATIONS { get; set; }
        public virtual ICollection<PERSON_JOBS> PERSON_JOBS { get; set; }
        public virtual ICollection<PERSON_LANGUAGES> PERSON_LANGUAGES { get; set; }
        public virtual ICollection<PERSON_MEDALS> PERSON_MEDALS { get; set; }
        public virtual ICollection<PERSON_MEASURES> PERSON_MEASURES { get; set; }
        public virtual ICollection<PERSON_PROPERTIES> PERSON_PROPERTIES { get; set; }
        public virtual ICollection<PERSON_PUNISHMENTS> PERSON_PUNISHMENTS { get; set; }
        public virtual ICollection<PERSON_PUNISHMENT_EXECUTION> PERSON_PUNISHMENT_EXECUTION { get; set; }
        public virtual ICollection<PERSON_RANKING_TESTS> PERSON_RANKING_TESTS { get; set; }
        public virtual ICollection<PERSON_RELIVANTS> PERSON_RELIVANTS { get; set; }
        public virtual ICollection<PERSON_REPORTS> PERSON_REPORTS { get; set; }
        public virtual ICollection<PERSON_SECRET_REPORTS> PERSON_SECRET_REPORTS { get; set; }
        public virtual ICollection<PERSON_STUDIES> PERSON_STUDIES { get; set; }
        public virtual ICollection<PERSON_SOCIAL_PROBLEMS> PERSON_SOCIAL_PROBLEMS { get; set; }
        public virtual ICollection<PERSON_UNIV_STUDIES> PERSON_UNIV_STUDIES { get; set; }
        public virtual ICollection<PERSON_VACATIONS> PERSON_VACATIONS { get; set; }
        public virtual ICollection<PERSON_VACATIONS> PERSON_VACATIONS1 { get; set; }
        public virtual ICollection<PERSON_VACATIONS> PERSON_VACATIONS2 { get; set; }
        public virtual ICollection<PERSON_VACATIONS> PERSON_VACATIONS3 { get; set; }
        public virtual ICollection<PERSON_VACATIONS> PERSON_VACATIONS4 { get; set; }
        public virtual ICollection<PERSON_VACATIONS> PERSON_VACATIONS5 { get; set; }
        public virtual ICollection<PERSONS_GIFTS> PERSONS_GIFTS { get; set; }
        public virtual ICollection<PERSONS_RANKING> PERSONS_RANKING { get; set; }
        public virtual ICollection<PERSONS_TRAVELS> PERSONS_TRAVELS { get; set; }
        public virtual ICollection<PERSONS_RELIVENTS_TRAVELS> PERSONS_RELIVENTS_TRAVELS { get; set; }
        public virtual ICollection<PERSON_PAYING_SYNDICATE> PERSON_PAYING_SYNDICATE { get; set; }
        public virtual ICollection<PERSON_PROGRAMMING_TOOLS> PERSON_PROGRAMMING_TOOLS { get; set; }
        public virtual ICollection<PERSON_PROJECTS> PERSON_PROJECTS { get; set; }
        public virtual ICollection<PERSON_VACATIONS_DET> PERSON_VACATIONS_DET { get; set; }
        public virtual VACATION_MODELS VACATION_MODELS { get; set; }
    }
}
