//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_MEDALS
    {
        public string PERSON_CODE { get; set; }
        public short SEQ { get; set; }
        public Nullable<short> MEDAL_TYPE_ID { get; set; }
        public string FIRM_CODE { get; set; }
        public Nullable<System.DateTime> MEDAL_DATE { get; set; }
        public string OWNER_PERMATION { get; set; }
        public string ORDER_NO { get; set; }
        public Nullable<System.DateTime> ORDER_DATE { get; set; }
        public string REASON { get; set; }
    
        public virtual PERSON_DATA PERSON_DATA { get; set; }
    }
}
