//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONS_MOVEMENT_ORDER_PERSONS
    {
        public string ORDER_NO { get; set; }
        public short ORDER_DEPARTMENT_ID { get; set; }
        public string ID_NO { get; set; }
        public string SORT_NO { get; set; }
        public Nullable<short> MOVEMENT_DIRECTION { get; set; }
        public Nullable<short> STEP_TYPE_ID { get; set; }
        public Nullable<System.DateTime> EXECUTION_DATE { get; set; }
        public string FROM_FIRM_CODE { get; set; }
        public string TO_FIRM_CODE { get; set; }
        public Nullable<short> RANK_ID { get; set; }
        public Nullable<short> RANK_CAT_ID { get; set; }
        public Nullable<short> PERSON_CAT_ID { get; set; }
        public Nullable<short> RAN_RANK_ID { get; set; }
        public Nullable<short> RAN_RANK_CAT_ID { get; set; }
        public Nullable<short> RAN_PERSON_CAT_ID { get; set; }
        public Nullable<short> JOB_TYPE_ID { get; set; }
        public Nullable<short> JOB_JOB_TYPE_ID { get; set; }
        public string PERSON_CODE { get; set; }
        public Nullable<short> DEPARTMENT_ID { get; set; }
        public string PERSON_NAME { get; set; }
        public Nullable<short> IS_PROCESSED { get; set; }
    
        public virtual FIRMS FIRMS { get; set; }
        public virtual FIRMS FIRMS1 { get; set; }
        public virtual PERSON_MOVEMENT_STEPS PERSON_MOVEMENT_STEPS { get; set; }
        public virtual PERSONS_MOVEMENT_ORDERS PERSONS_MOVEMENT_ORDERS { get; set; }
        public virtual RANKS RANKS { get; set; }
        public virtual RANKS RANKS1 { get; set; }
    }
}
