//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_SERVICE_TEMP
    {
        public Nullable<short> DAY_35 { get; set; }
        public Nullable<short> DAY_34 { get; set; }
        public Nullable<short> DAY_33 { get; set; }
        public Nullable<short> DAY_32 { get; set; }
        public Nullable<short> DAY_31 { get; set; }
        public Nullable<short> DAY_30 { get; set; }
        public Nullable<short> DAY_29 { get; set; }
        public Nullable<short> DAY_28 { get; set; }
        public Nullable<short> DAY_27 { get; set; }
        public Nullable<short> DAY_26 { get; set; }
        public Nullable<short> DAY_25 { get; set; }
        public Nullable<short> DAY_24 { get; set; }
        public Nullable<short> DAY_23 { get; set; }
        public Nullable<short> DAY_22 { get; set; }
        public Nullable<short> DAY_21 { get; set; }
        public Nullable<short> DAY_20 { get; set; }
        public Nullable<short> DAY_19 { get; set; }
        public Nullable<short> DAY_18 { get; set; }
        public Nullable<short> DAY_17 { get; set; }
        public Nullable<short> DAY_16 { get; set; }
        public Nullable<short> DAY_15 { get; set; }
        public Nullable<short> DAY_14 { get; set; }
        public Nullable<short> DAY_13 { get; set; }
        public Nullable<short> DAY_12 { get; set; }
        public Nullable<short> DAY_11 { get; set; }
        public Nullable<short> DAY_10 { get; set; }
        public Nullable<short> DAY_09 { get; set; }
        public Nullable<short> DAY_08 { get; set; }
        public Nullable<short> DAY_07 { get; set; }
        public Nullable<short> DAY_06 { get; set; }
        public Nullable<short> DAY_05 { get; set; }
        public Nullable<short> DAY_04 { get; set; }
        public Nullable<short> DAY_03 { get; set; }
        public Nullable<short> DAY_02 { get; set; }
        public Nullable<short> DAY_01 { get; set; }
        public Nullable<short> PERSON_VAC { get; set; }
        public Nullable<System.DateTime> VAC_BACK_DATE { get; set; }
        public Nullable<short> MIN_DURATION { get; set; }
        public Nullable<short> VACATION_DURATION { get; set; }
        public Nullable<short> VACATION_MODEL_ID { get; set; }
        public string PERSON_NAME { get; set; }
        public string PERSON_CODE { get; set; }
        public Nullable<System.DateTime> DATE_35 { get; set; }
        public Nullable<System.DateTime> DATE_34 { get; set; }
        public Nullable<System.DateTime> DATE_33 { get; set; }
        public Nullable<System.DateTime> DATE_32 { get; set; }
        public Nullable<System.DateTime> DATE_31 { get; set; }
        public Nullable<System.DateTime> DATE_30 { get; set; }
        public Nullable<System.DateTime> DATE_29 { get; set; }
        public Nullable<System.DateTime> DATE_28 { get; set; }
        public Nullable<System.DateTime> DATE_27 { get; set; }
        public Nullable<System.DateTime> DATE_26 { get; set; }
        public Nullable<System.DateTime> DATE_25 { get; set; }
        public Nullable<System.DateTime> DATE_24 { get; set; }
        public Nullable<System.DateTime> DATE_23 { get; set; }
        public Nullable<System.DateTime> DATE_22 { get; set; }
        public Nullable<System.DateTime> DATE_21 { get; set; }
        public Nullable<System.DateTime> DATE_20 { get; set; }
        public Nullable<System.DateTime> DATE_19 { get; set; }
        public Nullable<System.DateTime> DATE_18 { get; set; }
        public Nullable<System.DateTime> DATE_17 { get; set; }
        public Nullable<System.DateTime> DATE_16 { get; set; }
        public Nullable<System.DateTime> DATE_15 { get; set; }
        public Nullable<System.DateTime> DATE_14 { get; set; }
        public Nullable<System.DateTime> DATE_13 { get; set; }
        public Nullable<System.DateTime> DATE_12 { get; set; }
        public Nullable<System.DateTime> DATE_11 { get; set; }
        public Nullable<System.DateTime> DATE_10 { get; set; }
        public Nullable<System.DateTime> DATE_09 { get; set; }
        public Nullable<System.DateTime> DATE_08 { get; set; }
        public Nullable<System.DateTime> DATE_07 { get; set; }
        public Nullable<System.DateTime> DATE_06 { get; set; }
        public Nullable<System.DateTime> DATE_05 { get; set; }
        public Nullable<System.DateTime> DATE_04 { get; set; }
        public Nullable<System.DateTime> DATE_03 { get; set; }
        public Nullable<System.DateTime> DATE_02 { get; set; }
        public Nullable<System.DateTime> DATE_01 { get; set; }
        public Nullable<short> SELAH_SUM { get; set; }
        public Nullable<short> THAKHIRA_SUM { get; set; }
        public Nullable<short> HARAKA_SUM { get; set; }
        public Nullable<short> AGAZA_SUM { get; set; }
        public Nullable<short> PREVIOS_ABSENCE_COUNT { get; set; }
        public System.DateTime FROM_DATE { get; set; }
        public short DAYS_COUNT { get; set; }
    }
}
