//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_IT_PROJECT_INVOLVEMENT
    {
        public string PERSON_CODE { get; set; }
        public int PROJECT_SEQ { get; set; }
        public short INVOLVEMENT_TYPE_ID { get; set; }
        public Nullable<System.DateTime> INV_FROM { get; set; }
        public Nullable<System.DateTime> NV_TO { get; set; }
        public string NOTES { get; set; }
    
        public virtual PERSON_IT_PROJECTS PERSON_IT_PROJECTS { get; set; }
    }
}
