//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_SPECIALIZATIONS
    {
        public PERSON_SPECIALIZATIONS()
        {
            this.FIRM_PERSON_TOTALS = new HashSet<FIRM_PERSON_TOTALS>();
            this.PERSON_DATA = new HashSet<PERSON_DATA>();
        }
    
        public short SPECIALIZATION_ID { get; set; }
        public short CATEGORY_ID { get; set; }
        public string NAME { get; set; }
        public string SHORT_NAME { get; set; }
        public Nullable<decimal> ABSENCE_PERCENTAGE { get; set; }
    
        public virtual ICollection<FIRM_PERSON_TOTALS> FIRM_PERSON_TOTALS { get; set; }
        public virtual ICollection<PERSON_DATA> PERSON_DATA { get; set; }
        public virtual PERSON_SPEC_CATEGORIES PERSON_SPEC_CATEGORIES { get; set; }
    }
}
