//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_RELIVANT_PUNISHMENTS
    {
        public short SEQ { get; set; }
        public string PERSON_CODE { get; set; }
        public string PUNISHMENT_TYPE { get; set; }
        public string MISTAKES_TYPE { get; set; }
        public Nullable<System.DateTime> PUNISHMENT_DATE { get; set; }
        public string PUNISHMENT_DISC { get; set; }
        public Nullable<short> DURATION { get; set; }
        public Nullable<System.DateTime> PUNISHMENT_FINISH { get; set; }
        public short SERIAL { get; set; }
    }
}
