//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_ILLEGAL_ABSCENCES
    {
        public string PERSON_CODE { get; set; }
        public string FIRM_CODE { get; set; }
        public Nullable<short> RANK_ID { get; set; }
        public Nullable<short> RANK_CAT_ID { get; set; }
        public Nullable<short> PERSON_CAT_ID { get; set; }
        public System.DateTime ABSCENCE_FROM { get; set; }
        public string INFORM_FIRM_CODE { get; set; }
        public Nullable<System.DateTime> ABSCENCE_TO { get; set; }
        public string ACTION_TAKEN { get; set; }
        public string NOTES { get; set; }
    
        public virtual FIRMS FIRMS { get; set; }
        public virtual FIRMS FIRMS1 { get; set; }
        public virtual PERSON_DATA PERSON_DATA { get; set; }
        public virtual RANKS RANKS { get; set; }
    }
}
