//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_BATTELES
    {
        public short BATTLE_ID { get; set; }
        public string PERSON_CODE { get; set; }
        public string TASK { get; set; }
        public Nullable<System.DateTime> GAME_FROM { get; set; }
        public Nullable<System.DateTime> GAME_TO { get; set; }
        public string POSITION { get; set; }
    
        public virtual PERSON_DATA PERSON_DATA { get; set; }
    }
}
