//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSON_MOVEMENT_STEPS
    {
        public PERSON_MOVEMENT_STEPS()
        {
            this.PERSONS_MOVEMENT_ORDER_STEPS = new HashSet<PERSONS_MOVEMENT_ORDER_STEPS>();
            this.PERSONS_MOVEMENT_ORDER_PERSONS = new HashSet<PERSONS_MOVEMENT_ORDER_PERSONS>();
        }
    
        public short STEP_TYPE_ID { get; set; }
        public string STEP_NAME { get; set; }
    
        public virtual ICollection<PERSONS_MOVEMENT_ORDER_STEPS> PERSONS_MOVEMENT_ORDER_STEPS { get; set; }
        public virtual ICollection<PERSONS_MOVEMENT_ORDER_PERSONS> PERSONS_MOVEMENT_ORDER_PERSONS { get; set; }
    }
}
