//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROGRAMMING_TOOLS
    {
        public PROGRAMMING_TOOLS()
        {
            this.PERSON_PROGRAMMING_TOOLS = new HashSet<PERSON_PROGRAMMING_TOOLS>();
        }
    
        public short PROG_TOOL_CODE { get; set; }
        public string PROG_TOOL_NAME { get; set; }
    
        public virtual ICollection<PERSON_PROGRAMMING_TOOLS> PERSON_PROGRAMMING_TOOLS { get; set; }
    }
}
