//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJECTS
    {
        public PROJECTS()
        {
            this.PERSON_PROJECTS = new HashSet<PERSON_PROJECTS>();
        }
    
        public short PROJECT_CODE { get; set; }
        public string PROJECT_NAME { get; set; }
    
        public virtual ICollection<PERSON_PROJECTS> PERSON_PROJECTS { get; set; }
    }
}
