//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROPERTY_TYPES
    {
        public PROPERTY_TYPES()
        {
            this.PERSON_PROPERTIES = new HashSet<PERSON_PROPERTIES>();
        }
    
        public short PROPERTY_TYPE_ID { get; set; }
        public string PROPERTY_NAME { get; set; }
        public Nullable<short> DISPLAY_ORDER { get; set; }
    
        public virtual ICollection<PERSON_PROPERTIES> PERSON_PROPERTIES { get; set; }
    }
}
