//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_PARAM
    {
        public string PARA_NAME { get; set; }
        public string PARA_NAME_E { get; set; }
        public int ITEM_CODE { get; set; }
    }
}
