//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_VIEW_SESSION_NOTIF_MAP
    {
        public decimal SESSION_ID { get; set; }
        public string PRINCIPAL_NAME { get; set; }
        public decimal SEQUENCE_NUM { get; set; }
        public Nullable<decimal> NOTIFICATION_ID { get; set; }
        public Nullable<decimal> NOTIFICATION_TYPE { get; set; }
        public Nullable<decimal> SUBTYPE { get; set; }
        public string NODE_NAME { get; set; }
        public string SERVICE_NAME { get; set; }
        public string SERVICE_TYPE { get; set; }
        public Nullable<decimal> TIME_STAMP { get; set; }
        public Nullable<decimal> TIME_ZONE { get; set; }
        public Nullable<decimal> VERBOSE { get; set; }
        public string DOMAIN { get; set; }
    }
}
