//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_VDN_VIEW_BLACKOUTSCHEDULES
    {
        public Nullable<decimal> TARGETID { get; set; }
        public string TARGET_NAME { get; set; }
        public string TARGET_TYPE { get; set; }
        public string SCHEDULENAME { get; set; }
        public Nullable<decimal> SCHEDULESTATE { get; set; }
        public string SCHEDULE { get; set; }
        public string START_TIME { get; set; }
        public string END_TIME { get; set; }
        public Nullable<decimal> DURATION_LENGTH { get; set; }
        public Nullable<decimal> UNITS { get; set; }
        public Nullable<decimal> DURATION_MODE { get; set; }
        public Nullable<decimal> TOTALBLACKOUT { get; set; }
    }
}
