//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_VIEW_NODES
    {
        public string NODE_NAME { get; set; }
        public Nullable<decimal> DISCOVERY { get; set; }
        public Nullable<System.DateTime> LAST_CHECKED { get; set; }
        public Nullable<decimal> AGENT_STATUS { get; set; }
        public string OMS_MACHINE { get; set; }
        public string REGION { get; set; }
    }
}
