//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_VIEW_TOP_GROUPS
    {
        public string GROUP_NAME { get; set; }
        public string GROUP_OWNER { get; set; }
        public string DESCRIPTION { get; set; }
        public string BACKGROUND_IMAGE { get; set; }
        public Nullable<decimal> ICON_SIZE { get; set; }
    }
}
