//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_VIEW_SESSIONS
    {
        public string ADMINISTRATOR_NAME { get; set; }
        public string OMS_MACHINE { get; set; }
        public Nullable<System.DateTime> LOGIN_TIME { get; set; }
    }
}
