//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMP_VIEW_JOB_EXECUTIONS
    {
        public decimal JOB_ID { get; set; }
        public string JOB_NAME { get; set; }
        public string NODE_NAME { get; set; }
        public string TARGET_NAME { get; set; }
        public string TARGET_TYPE { get; set; }
        public string TARGET_NLS_TYPE { get; set; }
        public string ADMINISTRATOR_NAME { get; set; }
        public Nullable<decimal> EXEC_NUM { get; set; }
        public Nullable<System.DateTime> TIMESTAMP { get; set; }
        public Nullable<decimal> STATUS { get; set; }
    }
}
