//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAMAM_SH
    {
        public string PERSON_NAME { get; set; }
        public string PERSON_CODE { get; set; }
        public Nullable<short> RANK_ID { get; set; }
        public string RANK { get; set; }
        public string ID_NO { get; set; }
        public Nullable<System.DateTime> CURRENT_RANK_DATE { get; set; }
        public string SORT_NO { get; set; }
        public Nullable<short> CATEGORY_ID { get; set; }
        public Nullable<decimal> ABSENCE_TYPE_ID { get; set; }
        public Nullable<decimal> ABSENCE_COUNT { get; set; }
        public string NOTES { get; set; }
        public Nullable<decimal> ONE { get; set; }
        public Nullable<decimal> TWO { get; set; }
        public Nullable<decimal> THREE { get; set; }
        public Nullable<decimal> FOUR { get; set; }
        public Nullable<decimal> FIVE { get; set; }
        public Nullable<decimal> SIX { get; set; }
        public Nullable<decimal> SEVEN { get; set; }
        public Nullable<decimal> EIGHT { get; set; }
        public Nullable<decimal> NINE { get; set; }
        public Nullable<decimal> TEN { get; set; }
        public Nullable<decimal> ELEVEN { get; set; }
        public Nullable<decimal> TEWELVE { get; set; }
        public Nullable<decimal> THIRTEN { get; set; }
        public Nullable<decimal> FOURTEEN { get; set; }
        public Nullable<decimal> TOTAL_COUNT { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> TO_DATE { get; set; }
        public Nullable<System.DateTime> ENTRY_HOUR { get; set; }
        public Nullable<decimal> ABSENCE_TYPE_ID_Y { get; set; }
    }
}
