//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_TEST_LEVEL_PERSONS
    {
        public string FIN_YEAR { get; set; }
        public short TRAINING_PERIOD_ID { get; set; }
        public short TEST_LEVEL_ID { get; set; }
        public string FIRM_CODE { get; set; }
        public short SITE_ID { get; set; }
        public short SUBJECT_ID { get; set; }
        public string PERSON_CODE { get; set; }
        public Nullable<short> EXECUTION_STATUS_ID { get; set; }
        public Nullable<short> PERSON_DEGREE { get; set; }
        public Nullable<System.DateTime> EXAM_DATE { get; set; }
        public Nullable<short> RUN { get; set; }
        public Nullable<short> PRESS { get; set; }
        public Nullable<short> JUMP { get; set; }
        public Nullable<short> APDOMINAL { get; set; }
        public Nullable<short> OKLA { get; set; }
    
        public virtual TRAINING_TEST_LEVEL_SUBJECTS TRAINING_TEST_LEVEL_SUBJECTS { get; set; }
    }
}
