//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAIN_UNIT_TYPE_TRAIN_DAYS
    {
        public TRAIN_UNIT_TYPE_TRAIN_DAYS()
        {
            this.TRAIN_DEFAULT_HOURS = new HashSet<TRAIN_DEFAULT_HOURS>();
        }
    
        public short TRAIN_TYPE_CODE { get; set; }
        public short TMRKZ_STATUS { get; set; }
        public Nullable<short> DAYS_NO { get; set; }
    
        public virtual ICollection<TRAIN_DEFAULT_HOURS> TRAIN_DEFAULT_HOURS { get; set; }
        public virtual TRAIN_UNITS_TYPES TRAIN_UNITS_TYPES { get; set; }
    }
}
