//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAIN_DEFAULT_HOURS
    {
        public short TRAIN_TYPE_CODE { get; set; }
        public short TMRKZ_STATUS { get; set; }
        public short DAY_NO { get; set; }
        public Nullable<short> HOURS_NO { get; set; }
        public Nullable<short> NIGHT_HOURS_NO { get; set; }
        public string OTHER_ACTIVITY { get; set; }
    
        public virtual TRAIN_UNIT_TYPE_TRAIN_DAYS TRAIN_UNIT_TYPE_TRAIN_DAYS { get; set; }
        public virtual TRAIN_UNITS_TYPES TRAIN_UNITS_TYPES { get; set; }
    }
}
