//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAIN_UNIT_SPEC
    {
        public short TRAIN_SPEC_CODE { get; set; }
        public string TRAIN_SPEC_NAME { get; set; }
    }
}
