//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_PERIODS
    {
        public TRAINING_PERIODS()
        {
            this.ACCEDENTS = new HashSet<ACCEDENTS>();
            this.FIRM_MISSIONS = new HashSet<FIRM_MISSIONS>();
            this.FIRMS_ABSENCES = new HashSet<FIRMS_ABSENCES>();
            this.FIRMS_CALIBRATION_PLAN = new HashSet<FIRMS_CALIBRATION_PLAN>();
            this.FIRMS_INSPECT_PASS_PLAN = new HashSet<FIRMS_INSPECT_PASS_PLAN>();
            this.FIRMS_INSPECT_PASS_PLAN_DEPTS = new HashSet<FIRMS_INSPECT_PASS_PLAN_DEPTS>();
        }
    
        public string FIN_YEAR { get; set; }
        public short TRAINING_PERIOD_ID { get; set; }
        public string TRAINING_PERIOD { get; set; }
        public Nullable<System.DateTime> PERIOD_FROM { get; set; }
        public Nullable<System.DateTime> PERIOD_TO { get; set; }
    
        public virtual ICollection<ACCEDENTS> ACCEDENTS { get; set; }
        public virtual ICollection<FIRM_MISSIONS> FIRM_MISSIONS { get; set; }
        public virtual ICollection<FIRMS_ABSENCES> FIRMS_ABSENCES { get; set; }
        public virtual ICollection<FIRMS_CALIBRATION_PLAN> FIRMS_CALIBRATION_PLAN { get; set; }
        public virtual ICollection<FIRMS_INSPECT_PASS_PLAN> FIRMS_INSPECT_PASS_PLAN { get; set; }
        public virtual ICollection<FIRMS_INSPECT_PASS_PLAN_DEPTS> FIRMS_INSPECT_PASS_PLAN_DEPTS { get; set; }
        public virtual TRAINING_YEARS TRAINING_YEARS { get; set; }
    }
}
