//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_TESTS_SUBJECTS
    {
        public short SUBJECT_ID { get; set; }
        public string SUBJECT_NAME { get; set; }
        public Nullable<short> MAJOR_DEGREE { get; set; }
        public Nullable<short> MINOR_DEGREE { get; set; }
    }
}
