//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_TESTS
    {
        public TRAINING_TESTS()
        {
            this.TRAINING_TEST_LEVEL_SUBJECTS = new HashSet<TRAINING_TEST_LEVEL_SUBJECTS>();
            this.TRAINING_TESTS_PERSONS = new HashSet<TRAINING_TESTS_PERSONS>();
        }
    
        public string FIN_YEAR { get; set; }
        public short TRAINING_PERIOD_ID { get; set; }
        public short TEST_LEVEL_ID { get; set; }
        public string FIRM_CODE { get; set; }
        public short SITE_ID { get; set; }
        public Nullable<short> RANK_CAT_ID { get; set; }
        public Nullable<short> PERSON_CAT_ID { get; set; }
        public Nullable<System.DateTime> MAIN_START_DATE { get; set; }
        public Nullable<System.DateTime> MAIN_END_DATE { get; set; }
        public Nullable<System.DateTime> SPARE_START_DATE { get; set; }
        public Nullable<System.DateTime> SPARE_END_DATE { get; set; }
    
        public virtual FIRMS FIRMS { get; set; }
        public virtual RANK_CATEGORIES RANK_CATEGORIES { get; set; }
        public virtual ICollection<TRAINING_TEST_LEVEL_SUBJECTS> TRAINING_TEST_LEVEL_SUBJECTS { get; set; }
        public virtual ICollection<TRAINING_TESTS_PERSONS> TRAINING_TESTS_PERSONS { get; set; }
    }
}
