//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_COURSES_FIRMS
    {
        public short COURSE_TYPE_ID { get; set; }
        public string FIN_YEAR { get; set; }
        public short TRAINING_PERIOD_ID { get; set; }
        public short SEQ { get; set; }
        public string FIRM_CODE { get; set; }
        public Nullable<short> FIRM_QTY { get; set; }
    
        public virtual TRAINING_COURSES_PLAN TRAINING_COURSES_PLAN { get; set; }
    }
}
