//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_TEST_LEVEL_SUBJECTS
    {
        public TRAINING_TEST_LEVEL_SUBJECTS()
        {
            this.TRAINING_TEST_LEVEL_PERSONS = new HashSet<TRAINING_TEST_LEVEL_PERSONS>();
        }
    
        public string FIN_YEAR { get; set; }
        public short TRAINING_PERIOD_ID { get; set; }
        public short TEST_LEVEL_ID { get; set; }
        public string FIRM_CODE { get; set; }
        public short SITE_ID { get; set; }
        public short SUBJECT_ID { get; set; }
        public Nullable<short> MAJOR_DEGREE { get; set; }
        public Nullable<short> MINOR_DEGREE { get; set; }
    
        public virtual ICollection<TRAINING_TEST_LEVEL_PERSONS> TRAINING_TEST_LEVEL_PERSONS { get; set; }
        public virtual TRAINING_TESTS TRAINING_TESTS { get; set; }
    }
}
