//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CLASS_EXTENSIONS
    {
        public decimal ClassificationCode { get; set; }
        public string ClassificationName { get; set; }
        public string DTMF { get; set; }
        public string PERSON_CODE { get; set; }
        public string PERSON_NAME { get; set; }
        public string EXTENSION { get; set; }
        public Nullable<int> Agent_Order { get; set; }
    }
}
