//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WORKFLOW_APP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CURRENT_PERSON_DATA
    {
        public string PERSON_CODE { get; set; }
        public Nullable<short> RANK_ID { get; set; }
        public Nullable<short> DEPARTMENT_ID { get; set; }
        public Nullable<short> JOB_TYPE_ID { get; set; }
        public Nullable<short> GOVERNERATE_ID { get; set; }
        public Nullable<short> SECTOR_ID { get; set; }
        public Nullable<short> RELIGION_ID { get; set; }
        public Nullable<short> BLOOD_TYPE_ID { get; set; }
        public Nullable<short> AGE_CATEGORY_ID { get; set; }
        public Nullable<short> FACULTY_BRANCH_ID { get; set; }
        public Nullable<short> FACULTY_ID { get; set; }
        public Nullable<short> FAC_DEPARTMENT_ID { get; set; }
        public Nullable<short> UNIVERSITY_ID { get; set; }
        public Nullable<short> ID_TYPE_ID { get; set; }
        public Nullable<short> PARENT_STATUS_ID { get; set; }
        public string FIRM_CODE { get; set; }
        public Nullable<short> SOCIAL_STATE_ID { get; set; }
        public Nullable<short> RANK_CAT_ID { get; set; }
        public Nullable<short> PERSON_CAT_ID { get; set; }
        public Nullable<short> SPECIALIZATION_ID { get; set; }
        public Nullable<short> CATEGORY_ID { get; set; }
        public string PERSON_NAME { get; set; }
        public string ADDERESS { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public string PHONE1 { get; set; }
        public string PHONE_2 { get; set; }
        public string ID_NO { get; set; }
        public string SORT_NO { get; set; }
        public string BIRTH_PLACE { get; set; }
        public Nullable<short> SONS_COUNT { get; set; }
        public Nullable<short> DAUGHTERS_COUNT { get; set; }
        public Nullable<short> ARKAN_HARB { get; set; }
        public string COMMUNITY_NO { get; set; }
        public Nullable<short> MARRIGE_CONT { get; set; }
        public Nullable<short> SEX { get; set; }
        public Nullable<System.DateTime> JOIN_DATE { get; set; }
        public Nullable<System.DateTime> LEAVE_DATE { get; set; }
        public Nullable<System.DateTime> NEXT_RANK_DATE { get; set; }
        public Nullable<System.DateTime> CURRENT_RANK_DATE { get; set; }
        public string GRADUATION_NAME { get; set; }
        public Nullable<System.DateTime> REDEEF_DATE { get; set; }
        public Nullable<short> CLT_ID { get; set; }
        public Nullable<short> CERTIFICATE { get; set; }
        public Nullable<System.DateTime> HIRE_DATE { get; set; }
        public Nullable<short> OUT_UN_FORCE { get; set; }
        public Nullable<short> EDUCATION_LEVEL_ID { get; set; }
        public Nullable<short> EDUCATION_CERTIFICATE_ID { get; set; }
        public Nullable<short> EDUCATION_SPEC_ID { get; set; }
        public Nullable<short> CIVIL_JOB_ID { get; set; }
        public Nullable<short> SHOE_SIZE { get; set; }
        public string SUIT_SIZE { get; set; }
        public Nullable<short> OVERALL_SIZE { get; set; }
        public string MASK_SIZE { get; set; }
        public Nullable<short> RESIGN_REQUEST { get; set; }
        public Nullable<System.DateTime> RESIGN_REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> RESIGN_ACCEPTANCE_DATE { get; set; }
        public Nullable<System.DateTime> RANK_RENEW_DATE { get; set; }
        public Nullable<short> FEED_REPLACE { get; set; }
        public Nullable<short> SECONDRY_JOB_TYPE_ID { get; set; }
        public Nullable<short> RECRUTING_REGION_ID { get; set; }
        public string PERSONAL_ID_NO { get; set; }
        public Nullable<short> FIELD_SERVICE_ABILITY { get; set; }
        public Nullable<short> OUT_SERVICE_REASON_ID { get; set; }
        public Nullable<short> VACATION_MODEL_ID { get; set; }
        public Nullable<short> BORROW_STATUS { get; set; }
        public Nullable<short> SPECIALIZATION_LEVEL_ID { get; set; }
        public string BORROW_FIRM_CODE { get; set; }
        public string PRACTICAL_EXPERIENCE { get; set; }
        public Nullable<short> IS_READYTOEXAM { get; set; }
        public string BORROW_ORDER_NO { get; set; }
        public string DEATH_PLACE { get; set; }
        public string DEATH_REASON { get; set; }
        public Nullable<System.DateTime> DEATH_DATE { get; set; }
        public string OUT_SERVICE_ORDER_NO { get; set; }
        public Nullable<System.DateTime> OUT_SERVICE_ORDER_DATE { get; set; }
        public string APLLICATION_21_NO { get; set; }
        public string APLLICATION_26_NO { get; set; }
        public Nullable<short> DEPT_CODE { get; set; }
        public Nullable<short> BRANCH_CODE { get; set; }
        public Nullable<short> PAYING_SYNDICATE_SITUATION { get; set; }
        public string SYNDICATE_NAME { get; set; }
        public string ARC_CODE { get; set; }
        public Nullable<int> ARC_SERIAL { get; set; }
        public string SARYA { get; set; }
        public string EFADA_CODE { get; set; }
        public Nullable<System.DateTime> EFADA_DATE { get; set; }
        public string AMN_STATE { get; set; }
        public string NAFSY { get; set; }
        public string ADDERESS2 { get; set; }
        public Nullable<System.DateTime> NOZOM_DATE { get; set; }
        public Nullable<int> WEAPON_NO { get; set; }
        public string EXTENSION { get; set; }
    }
}
